app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
Route::post('actors/connect', 'ActorsController@postConnect');

Route::resource('actors', 'ActorsController');
Route::resource('movies', 'MoviesController');


Route::get('/', function () {
  return View::make('home')->withTitle('Movies DB - Home');
});

app/models/Actor.php
<?php

class Actor extends srdjan\neo4l\Neo4l {
  protected $fillable = [];

  /**
   * Get all actors and number of the roles they played
   * @return array
   */
  public function all() {
    $query = $this->client->query("MATCH (actor:Person)
                                      OPTIONAL MATCH (actor)-[role:ACTED_IN]->(movie:Movie)
                                      WITH length(role.roles) as roleCount, actor
                                      RETURN sum(roleCount) as totalRoleCount, actor
                                      ORDER BY totalRoleCount DESC;");
    $results = [];
    foreach ($query as $key => $row) {
      $results[$key]['actor'] = $row['actor'];
      $results[$key]['totalRoleCount'] = $row['totalRoleCount'];
    }

    return $results;
  }

  /**
   * Get actor details by his/hers name,
   * @param str $name
   * @return array 'movies', 'coactors'
   */
  public function single($name) {
    $results = [];

    // Get actor details, coactors, movies in which they coacted and order by time they coacted
    $query = $this->client->query('MATCH (actor:Person{name:"' . $name . '"})-[role:ACTED_IN]->(movies)<-[r:ACTED_IN]-(coactors)
                                       WITH actor, coactors, count(coactors) as TimesCoacted, collect(DISTINCT movies) as movies
                                       RETURN movies, coactors.name, avg(TimesCoacted) as TimesCoacted
                                       ORDER BY TimesCoacted DESC');

    $coactors = [];
    foreach ($query as $key => $row) {
      $coactors[] = $row;
    }

    //Unset the $query to reuse it
    unset($query);

    //Get movies for actor, along with all roles he or she played in it
    $query = $this->client->query('MATCH (actor:Person {name:"' . $name . '"})-[role:ACTED_IN]->(movies)
                                       WITH actor, movies, role
                                       ORDER BY movies.released DESC
                                       RETURN actor, collect({roles: role.roles, movies: movies}) as movies');
    $movies = [];
    foreach ($query as $key => $row) {
      $movies[] = $row;
    }

    $results['movies'] = $movies;
    $results['coactors'] = $coactors;

    return $results;
  }

  /**
   * Create new actor
   * @param array $vars 'name' and 'born'
   * @return array
   */
  public function create_new($vars) {
    $name = $vars['name'];
    $born = $vars['born'];

    $query = $this->client->query('CREATE (actor:Person{name:"' . $name . '", born:"' . $born . '"})');
    return array('code' => $query->errorCode(), 'info' => $query->errorInfo());
  }

  /**
   * Get basic info for an actor
   * @param str $name
   * @return array
   */
  public function info($name) {
    $results = $this->client->query('MATCH (actor:Person{name:"' . $name . '"})
                                         RETURN actor');
    foreach ($results as $row) {
      $actor['name'] = $row['actor']['name'];
      $actor['born'] = (!empty($row['actor']['born'])) ? $row['actor']['born'] : '';
    }

    return $actor;
  }

  /**
   * Edit an actor
   * @param array $data 'old_name' to alter with the 'new_name'
   * @return array
   */
  public function edit($data) {
    $query = $this->client->query('MATCH (actor:Person{name:"' . $data['old_name'] . '"})
                                   SET actor.name = "' . $data['new_name'] . '"
                                   SET actor.born = "'.$data['born'].'"
                                   RETURN actor');
    return array('code' => $query->errorCode(), 'info' => $query->errorInfo());
  }

  /**
   * Delete an actor and all his/hers relationships, if it has any
   * @param str $name
   * @return array
   */
  public function delete($name) {
    $query = $this->client->query('MATCH (actor{name:"' . $name . '"})
                                   OPTIONAL MATCH (actor)-[r]-()
                                   DELETE actor, r');
    return array('code' => $query->errorCode(), 'info' => $query->errorInfo());
  }
}

app/controllers/ActorsController.php
<?php

class ActorsController extends BaseController {

  /**
   * The layout that should be used for responses.
   */
  protected $layout = 'layouts.default';
  protected $actor;
  protected $movie;

  public function __construct(Actor $actor, Movie $movies) {
    $this->actor = $actor;
    $this->movie = $movies;
  }

  /**
   * Display a listing of the resource.
   * GET /actors
   *
   * @return Response
   */
  public function index() {
    $actors = $this->actor->all();
    return View::make('actors.index', compact('actors'))
      ->withTitle("MovieDB - Actors")
      ->withMessage(Session::get('message'));
  }

  /**
   * Show the form for creating a new resource.
   * GET /actors/create
   *
   * @return Response
   */
  public function create() {
    return View::make('actors.create')
      ->withTitle("MovieDB - Create new actor");
  }

  /**
   * Store a newly created resource in storage.
   * POST /actors
   *
   * @return Response
   */
  public function store() {
    //Check if request is indeed ajax
    if (Request::ajax()) {

      //Try to add new record
      $result = $this->actor->create_new(Input::all());

      //Check if there were any errors
      if ($result['code'] == '00000') {
        //Just return that everything is OK
        return 'OK';
      }
      else {
        //If there were, return error info:
        return 'Error code: ' . $result['code'] . "<br>" .
        'Error info: ' . $result['info'];
      }
    }
  }

  /**
   * Display the specified resource.
   * GET /actors/{name}
   *
   * @param  str $name
   * @return Response
   */
  public function show($name) {
    $result = $this->actor->single($name);

    $actor = reset($result['movies'])['actor'];

    foreach ($result['coactors'] as $key => $item) {
      $coactors[$key]['name'] = $item['coactors.name'];
      $coactors[$key]['movies'] = $item['movies'];
      $coactors[$key]['times-coacted'] = $item['TimesCoacted'];
    }

    foreach (reset($result['movies'])['movies'] as $key => $item) {
      $movies[$key]['title'] = $item['movies']['title'];
      $movies[$key]['tagline'] = !empty($item['movies']['tagline']) ? $item['movies']['tagline'] : '';
      $movies[$key]['released'] = $item['movies']['released'];
      $movies[$key]['roles'] = $item['roles'];
    }

    return View::make('actors.single')
      ->withActor($actor)
      ->withCoactors($coactors)
      ->withMovies($movies)
      ->withTitle("MovieDB - {$name}");
  }

  /**
   * Show the form for editing the specified resource.
   * GET /actors/{$name}/edit
   *
   * @param  string $name
   * @return Response
   */
  public function edit($name) {
    $actor = $this->actor->info($name);
    $movies = $this->movie->all();
    return View::make('actors.edit')
      ->withTitle('Movies DB - Edit ' . $actor['name'])
      ->withActor($actor)
      ->withMovies($movies)
      ->withMessage(Session::get('message'));
  }

  /**
   * Update the specified resource in storage.
   * PUT /actors/{old_name}/{name}
   *
   * @return Response
   */
  public function update() {
    $old_name = Input::get('old_name');
    $new_name = Input::get('name');
    $born = Input::get('born');
    //Try to edit record
    $result = $this->actor->edit([
      'old_name' => $old_name,
      'new_name' => $new_name,
      'born' => $born,
    ]);

    //Check if there were any errors
    if ($result['code'] == '00000') {
      $message['text'] = 'Actor edited successfully!';
      $message['class'] = 'alert-success changed';
      //Redirect to the new name actor page
      return Redirect::route('actors.edit', [$new_name])->withMessage($message);
    }
    else {
      //If there were, return error info:
      $message['text'] = 'There was an error!<br>';
      $message['text'] .= 'Error code: ' . $result['code'] . "<br>";
      $message['text'] .= 'Error info: ' . $result['info'];
      $message['class'] = 'alert-danger changed';
      return Redirect::route('actors.edit', [$old_name])->withMessage($message);
    }
  }

  /**
   * Remove the specified resource from storage.
   * DELETE /actors/{$name}
   *
   * @param  string $name
   * @return Response
   */
  public function destroy($name) {
    $result = $this->actor->delete($name);
    //Check if there were any errors
    if ($result['code'] == '00000') {
      $message = 'OK';
    }
    else {
      //If there were, return error info:
      $message = 'There was an error!<br>';
      $message .= 'Error code: ' . $result['code'] . "<br>";
      $message .= 'Error info: ' . $result['info'];
    }

    return $message;
  }


  /**
   * Helper function to get or set actors roles in a movie
   *
   * @return string
   */
  public function postConnect() {
    if (Request::ajax()) {
      switch (Input::get('action')) {
        case 'list':
          $results = $this->movie->getActorRolesInMovie(Input::get('actor'), Input::get('movie'));
          if ($results['roles']) {
            return implode(', ', $results['roles']);
          }
          else {
            return [];
          }
          break;
        case 'write':
          $result = $this->movie->setActorRolesInMovie(Input::get('actor'), Input::get('movie'), Input::get('roles'));

          //Check if there were any errors
          if ($result['code'] == '00000') {
            //Just return that everything is OK
            return 'OK';
          }
          else {
            //If there were, return error info:
            return 'Error code: ' . $result['code'] . "<br>" .
            'Error info: ' . $result['info'];
          }
          break;
        default:
          return 'no method';
          break;
      }
    }
  }

}

app/views/actors/actorToMovies.blade.php
<table class="moviesConnect table-striped table-bordered table-condensed">
<thead>
    <tr>
      <th colspan="2">Movies to test connect with:</th>
    </tr>
</thead>
<tbody>
    @foreach($movies as $movie)
    <tr>
        <td>{{ $movie['title'] }}({{ $movie['released'] }})</td>
        <td><a href="#" class="btn btn-primary btn-connect" data-toggle="modal" data-target="#actorMovieConnectModal" data-rel="{{ $movie['title'] }}"><span class="glyphicon glyphicon-link"></span>Connect</a></td>
    </tr>
    @endforeach
</tbody>
</table>

app/views/actors/create.blade.php
@extends('layouts.default')

@section('content')
    <h1>Add new Actor</h1>

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Actor details</h3>
        </div>
        <div class="panel-body">
            <div id="alerts" class="alert alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                <div class="message"></div>
            </div>

            {{ Form::open(array('route' => 'actors.store', 'class'=>'form-inline', 'id' => 'actor-create')) }}
            <div class="form-group">
                {{ Form::label('name', 'Name:') }}
                {{ Form::text('name', '', ['class'=>'form-control', 'size'=> '100']) }}

                {{ Form::label('born', 'Year born:') }}
                {{ Form::text('born', '', ['class'=>'form-control', 'size'=> '4']) }}
                {{ Form::submit('Add', ['id' => 'add-btn', 'class'=>'form-control btn btn-success']) }}
            </div>
            {{ Form::close() }}
            <hr/>
            <div class="controls pull-right">
                {{ link_to_route('actors.index', 'Back to all', [], ['class' => 'btn btn-default']) }}
                <a href="/actors/" id="edit-entity" class="btn btn-warning hidden">Edit actor</a>
                {{ link_to_route('actors.create', 'Add another', [], ['class' => 'btn btn-primary hidden', 'id'=>'add-another']) }}
            </div>
        </div>
    </div>



@stop

app/views/actors/edit.blade.php
@extends('layouts.default')

@section('content')
    <h1>Edit {{ $actor['name']; }}</h1>

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Actor details</h3>
      </div>
      <div class="panel-body">
        <div id="alerts" class="alert alert-dismissible @if(isset($message['class'])) {{ $message['class'] }} @endif" role="alert">
         <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true" >&times;</span></button>
                <div class="message">
                  @if(isset($message['text']))
                        {{ $message['text'] }}
                  @endif
                </div>
        </div>

        {{ Form::open(array('method' => 'PUT', 'route' => 'actors.update', 'class'=>'form-inline')) }}
            <div class="form-group">
                {{ Form::label('name', 'Name:') }}
                {{ Form::text('name', $actor['name'], ['class'=>'form-control', 'size'=> '100']) }}
                {{ Form::hidden('old_name', $actor['name']) }}

                {{ Form::label('born', 'Year born:') }}
                {{ Form::text('born', $actor['born'], ['class'=>'form-control', 'size'=> '4']) }}
                {{ Form::submit('Edit', ['id' => 'edit-btn', 'class'=>'form-control btn btn-success']) }}
            </div>
        {{ Form::close() }}

          <hr/>
          <div class="moviesConnect">
              <table class="table table-striped table-bordered table-condensed">
                  <thead>Connect with a movie:</thead>
                   <tbody>
                       @foreach($movies as $movie)
                        <tr>
                            <td> {{ link_to_route('movies.show', $movie['movie']['title'], [$movie['movie']['title']]) }} ({{ $movie['movie']['released'] }}) </td>
                            <td><a class="actorToMovie btn btn-primary" href="#" data-toggle="modal" data-target="#actorMovieConnectModal" data-movie="{{ $movie['movie']['title'] }}" data-actor="{{ $actor['name'] }}">Connect</a></td>
                        </tr>
                       @endforeach
                   </tbody>
              </table>
          </div>
          <hr/>
      {{ link_to_route('actors.index', 'Back to all actors', [], ['class' => 'btn btn-default pull-right']) }}
      </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="actorMovieConnectModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        {{ Form::label('name', 'Roles:') }}
                        {{ Form::text('roles', '', ['class'=>'form-control', 'size'=> '100']) }}
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary btn-save">Save changes</button>
                </div>
            </div>
        </div>
    </div>

@stop

app/views/actors/index.blade.php
@extends('layouts.default')

@section('content')
    <br/>
    {{ link_to_route('actors.create', 'Create new', [], ['class' => 'btn btn-primary pull-right']) }}

    <h1>Actors</h1>
    <div id="alerts" class="alert alert-dismissible @if(isset($message['class'])) {{ $message['class'] }} @endif" role="alert">
            <div class="message"></div>
        </div>
    <table class="actors table table-striped table-condensed">
        <thead>
            <tr>
                <th class="name">Name:</th>
                <th class="year">Year born:</th>
                <th class="roles-count">Roles played:</th>
                <td colspan="2"></td>

            </tr>
        </thead>
        <tbody>
        @foreach($actors as $actor)

        @if(!isset($actor['actor']['name']))

        <?php kd($actor); ?>
        @endif
            <tr>
               <td class="name">
                    <a href="/actors/{{$actor['actor']['name']}}">{{ $actor['actor']['name'] }}</a>
               </td>
               <td class="year">
                    @if(isset($actor['actor']['born']))
                        {{ $actor['actor']['born'] }}
                    @else
                        N/A
                    @endif
               </td>
               <td class="roles-count">
                    {{ $actor['totalRoleCount'] }}
               </td>
               <td>
                   {{ link_to_route('actors.edit', 'Edit', [$actor['actor']['name']], ['class' => 'btn btn-xs btn-warning']) }}
               </td>
               <td>
                   <a href="#" class="btn btn-xs btn-danger delete-btn" data-toggle="modal" data-target="#confirm-delete" data-entity-type="actors" data-entity="{{ $actor['actor']['name'] }}">Delete</a>
               </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    Confirm Delete
                </div>
                <div class="modal-body">
                   <p>You are about to delete an actor, this procedure is irreversible.</p>
                    <p>Do you want to proceed?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-danger btn-ok">Delete</a>
                </div>
            </div>
        </div>
    </div>

@stop

app/views/actors/single.blade.php
@extends('layouts.default')

@section('content')
<h1> {{ $actor['name'] }} @if(isset($actor['born'])) ({{ $actor['born'] }})@endif  </h1>
<hr/>
<div class="panel panel-primary">
  <div class="panel-heading">Acted in</div>
  <table class="actor-movies table table-striped table-bordered table-condensed">
      <thead>
          <tr>
              <th class="title">Title:</th>
              <th class="tagline">Tagline:</th>
              <th class="roles">Roles:</th>
          </tr>
      </thead>
      <tbody>
      @foreach($movies as $movie)
          <tr>
              <td><a href="/movies/{{ $movie['title'] }}">{{ $movie['title'] }} @if(isset($movie['released'])) ({{ $movie['released'] }}) @endif </a></td>
              <td>@if(!empty($movie['tagline'])) <em>"{{ $movie['tagline'] }}"</em> @endif</td>
              <td>
                  @foreach($movie['roles'] as $role)
                    {{ $role }}<br/>
                  @endforeach
              </td>
          </tr>
      @endforeach
      </tbody>
  </table>
</div>

<div class="panel panel-info">
  <div class="panel-heading">Acted with</div>

    <table class="actor-coactors table table-striped table-bordered able-condensed">
        <thead>
            <tr>
                <th class="coactor">Name:</th>
                <th class="movies">Movies in which they coacted:</th>
            </tr>
        </thead>
        <tbody>
        @foreach($coactors as $coactor)
            <tr>
                <td><a href="/actors/{{ $coactor['name'] }}">{{ $coactor['name'] }}</a></td>
                <td>
                    @foreach($coactor['movies'] as $movie)
                        <a href="/movies/{{ $movie['title'] }}">{{ $movie['title'] }} @if(isset($movie['released'])) ({{ $movie['released'] }}) @endif </a><br/>
                    @endforeach
                </td>
            </tr>
        @endforeach
        </tbody>

    </table>
</div>
@stop